name: nocternal
region: nyc
services:
- environment_slug: static-site
  github:
    branch: main
    deploy_on_push: true
    repo: nethrose/nocternal
  http_port: 80
  name: nocternal
  routes:
  - path: /
