name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Generate package.json
      run: |
        cd backend
        echo '{
          "name": "backend",
          "version": "1.0.0",
          "scripts": {
            "start": "node index.js"
          },
          "dependencies": {
            "express": "^4.17.1",
            "pg": "^8.7.1",
            "timescaledb": "^0.3.1"
          }
        }' > package.json

    - name: Install dependencies
      run: |
        cd backend
        npm ci
