name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 14
        
    - name: Install dependencies
      run: |
        cd backend
        echo '{
          "name": "backend",
          "version": "1.0.0",
          "scripts": {
            "start": "node app.js",
            "test": "jest --detectOpenHandles"
          },
          "dependencies": {
            "cors": "^2.8.5",
            "dotenv": "^10.0.0",
            "express": "^4.17.1",
            "pg": "^8.7.1"
          },
          "devDependencies": {
            "jest": "^27.4.7",
            "supertest": "^6.3.0"
          }
        }' > package.json
        npm install
        
    - name: Get runner IP
      id: get-ip
      run: echo "RUNNER_IP=$(curl -s https://ipinfo.io/ip)" >> $GITHUB_ENV

    - name: Install jq
      run: sudo apt-get install jq

    - name: Get current trusted sources
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        response=$(curl -s -X GET "https://api.digitalocean.com/v2/databases/${{ secrets.DATABASE_ID }}/firewall" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN")
        current_rules=$(echo "$response" | jq '.rules')
        echo "CURRENT_RULES=$(echo $current_rules | base64 --wrap=0)" >> $GITHUB_ENV

    - name: Add and verify trusted source
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        updated_rules=$(echo $CURRENT_RULES | base64 --decode | jq --arg ip "$RUNNER_IP" '. + [{"type": "ip_addr", "value": $ip}]')
        response=$(curl -i -X PUT "https://api.digitalocean.com/v2/databases/${{ secrets.DATABASE_ID }}/firewall" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" \
        -d "{\"rules\": $updated_rules}")
        echo "$response"
        echo "$response" | grep "HTTP/2 204" || exit 1
   
    - name: Verify trusted source added
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        response=$(curl -s -X GET "https://api.digitalocean.com/v2/databases/${{ secrets.DATABASE_ID }}/firewall" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN")
        echo "$response" | jq --arg ip "$RUNNER_IP" 'any(.rules[]; .type == "ip_addr" and .value == $ip)' | grep "true" || exit 1

    - name: Run tests
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        cd backend
        npm run test

    - name: Start the application
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        cd backend
        timeout 5s npm start || true
        
    - name: Check if app is running
      id: check_app
      run: |
        cd backend
        for i in {1..10}; do
          curl -s -o /dev/null -w '%{http_code}' http://localhost:3001 | grep -q 200 && echo "App is running" && exit 0
          sleep 5
        done
        echo "App is not running"
        exit 1
        
    - name: Remove trusted source
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
      if: always()
      run: |
        updated_rules=$(echo $CURRENT_RULES | base64 --decode | jq --arg ip "$RUNNER_IP" 'map(select(.value != $ip))')
        response=$(curl -i -X PUT "https://api.digitalocean.com/v2/databases/${{ secrets.DATABASE_ID }}/firewall" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" \
        -d "{\"rules\": $updated_rules}")
        echo "$response"
        echo "$response" | grep "HTTP/2 204" || exit 1
