name: Collector CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/collector/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/collector/**'

jobs:
  build_and_test_collector:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build OpenTelemetry Collector image
      uses: docker/build-push-action@v2
      with:
        context: backend/collector
        tags: nocternal/otel-collector:test

    - name: Start OpenTelemetry Collector container
      run: |
        docker run -d --name otel_collector \
          -v "$(pwd)/backend/collector/otel-collector-config.yaml:/otel-collector-config.yaml" \
          --expose 55681 \
          --expose 4317 \
          nocternal/otel-collector:test \
          --config otel-collector-config.yaml

    - name: Test collector is running
      run: |
        # Allow some time for the collector to start
        sleep 10
        # Check if the container is running
        if ! docker ps | grep otel_collector; then
          echo "Collector container is not running"
          exit 1
        fi

    - name: Stop and remove collector container
      if: always()
      run: |
        docker stop otel_collector
        docker rm otel_collector
