name: Test DO Connection

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get runner IP
      id: get-ip
      run: echo "RUNNER_IP=$(curl -s https://ipinfo.io/ip)" >> $GITHUB_ENV

    - name: Add trusted source
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        response=$(curl -i -X PUT "https://api.digitalocean.com/v2/databases/${{ secrets.DATABASE_ID }}/firewall" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" \
        -d '{"rules": [{"type": "ip_addr", "value": "${RUNNER_IP}"}]}')
        echo "$response"
        echo "$response" | grep "HTTP/2 201" || exit 1

    - name: Verify trusted source
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        response=$(curl -s -X GET "https://api.digitalocean.com/v2/databases/${{ secrets.DATABASE_ID }}/firewall" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN")
        echo "$response"
        echo "$response" | grep "${RUNNER_IP}" || exit 1

    - name: Remove trusted source
      if: always()
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        response=$(curl -i -X PUT "https://api.digitalocean.com/v2/databases/${{ secrets.DATABASE_ID }}/firewall" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $DIGITALOCEAN_ACCESS_TOKEN" \
        -d '{"rules": [{"type": "ip_addr", "value": "${RUNNER_IP}"}]}')
        echo "$response"
        echo "$response" | grep "HTTP/2 201" || exit 1
